### PR TITLE
Revision 2

### PR DESCRIPTION
**Pull request by ElectronicTeaCup**
All the changes from [revision_1](https://github.com/psychoinformatics-de/paper-remodnav/pull/10) and setting off some edits for revision 2.

### CODE REVIEW

**Comment by adswa** [comment]
Thanks for the start and the  [google doc](https://docs.google.com/document/d/1pG2oidzAfjlu_4piqzhuGOM9mCI-YWFK09ZvRlVpCfg/edit), @ElectronicTeaCup! I will push further changes to this branch.

Noting a future todo: I believe there is at least one unpushed tag lying around in @mih fork (resubmission1)

**Comment by adswa** [comment]
FTR: I have rebased this branch onto the ´revision_1` branch. `revision_1` and `preprint` (which this PR was based on before), had identical edits apart from stripping the BRMs formatting. With the rebase, we should have BRMs formatting.

Once this PR is complete, I suggest merging it into `preprint` from the command line and tagging it (`resubmission2`) as done with `revision_1`. Should the resubmission be accepted, I propose merging this PR into master (not `preprint`, as currently specified). Doing all of the above should bring master up-to-date with a hopefully accepted manuscript, and preprint up to date with our revisions.

**Comment by ElectronicTeaCup** [comment]
>Should the resubmission be accepted, I propose merging this PR into master (not `preprint`, as currently specified -- @ElectronicTeaCup this is something you would need to change, it can be done by editing the information right underneath the title of the PR). Doing all of the above should bring master up-to-date with a hopefully accepted manuscript, and preprint up to date with our revisions.

Got it, the PR is now headed towards merging with master now.

**Comment by adswa** [comment]
Thanks!

**Comment by adswa** [comment]
Alrighty, from my side this is ready to go. Here are left-over TODOs:

- [ ] @mih, if you haven't done so yet, please push the tag "resubmission1"
- [ ] for all: please read the manuscript and voice any concern you may have (and, ideally, suggest and apply changes)
- [ ] for all: please read the [response letter](https://docs.google.com/document/d/1pG2oidzAfjlu_4piqzhuGOM9mCI-YWFK09ZvRlVpCfg/edit) and voice any concern you may have (and, ideally, suggest and apply changes)
- [ ] Once happy with the changes in this repo, tag the topmost commit ('resubmission2')
- [ ] merge this branch into the preprint branch, compile the manuscript, and update the BioRxiv preprint. A summary of changes for the upload can be taken from the letter to the editor from the first page of the response.
- [ ] create a diff PDF between the tags `resubmission` and `resubmission2`
- [ ] resubmit! :tada:

**Pull request merged**
